export const items = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Behold the buttermilk pancakes, the fluffy ambassadors of morning delight! These pancakes are so light, they make feathers jealous. Infused with the essence of dreams and sprinkled with stardust, each bite is a journey to the breakfast galaxy. They're so good that even the sun hits snooze to savor their golden warmth. Warning: may cause spontaneous pancake poetry and morning happiness overload.`,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Introducing the diner double, the dynamic duo of lunchtime satisfaction! These burgers are so epic; they have their own theme music. Imagine a symphony of flavors, orchestrated by a culinary maestro. One bite and you'll be doing the flavor mambo. They're so good; even your taste buds will high-five each other in celebration.`,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Prepare yourself for the Godzilla milkshake, a shake so colossal it makes skyscrapers jealous! With every sip, you'll feel like you're in the midst of a delicious shakequake. It's the only milkshake endorsed by kaijus worldwide. Warning: consuming may lead to spontaneous Godzilla impersonations and uncontrollable yum-induced roars.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Enter the country delight, where rustic meets fantastic in a symphony of flavors. These breakfast delights are so charming; even roosters wake up early to savor them. Picture a countryside feast on a plate, complete with a side of nostalgia. It's like a warm hug from your favorite grandma, minus the cheek-pinching. Get ready for a taste journey to the heart of flavor country!`,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Get ready for the egg attack, where flavor bombs detonate in your mouth with every bite! These eggs are so rebellious; even the toast can't contain them. It's a lunchtime rebellion against blandness, featuring a coalition of flavors that will overthrow your taste expectations. Warning: May cause a coup d'état against your previous favorite lunch items.`,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Step into the Oreo dream, a milkshake so heavenly it's endorsed by the Cookie Angels Association. Each sip is like a bedtime story told by chocolate fairies. It's so dreamy; even sandman takes a break to savor it. Warning: May induce sweet dreams and a longing for bedtime milkshake rituals.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Behold the bacon overflow, where bacon rains from the breakfast heavens in a savory downpour! Each strip is a crispy superhero, ready to rescue your taste buds from blandness. It's so good; even eggs salute its sizzling glory. Warning: May cause bacon-themed daydreams and a sudden urge to declare your love for breakfast.`,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Introducing the American classic, a lunchtime legend that's as iconic as Elvis riding a unicorn. These flavors are so patriotic; even the bald eagle approves. It's like a star-spangled dance party in your mouth, complete with fireworks of deliciousness. Warning: May induce spontaneous flag-waving and a surge of national pride.`,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Meet the quarantine buddy, a shake so loyal it'll stick with you through thick and thin, or until the last sip. It's the ultimate comfort drink, like a virtual hug for your taste buds. With every sip, you'll feel like you have a personal shake confidante. Warning: May lead to nostalgic reflections and a newfound appreciation for the simple joys of shaking things up.`,
  },
];